
package View;

import java.awt.*;
import java.util.*;
import javax.imageio.ImageIO;
import javax.swing.*;

/**
 *
 * @author NHT_Kurumi
 */
public class JFrameTrangChu extends javax.swing.JFrame {

    private JPanelBanHang bhJPanel;
    private JPanelSanPham spJPanel;
    private JPanelHoaDon hdJPanel;
    private JPanelThongKe tkJPanel;
    private JPanelPhieuNhap pnJPanel;
    /**
     * Creates new form TrangChuView
     */
    public JFrameTrangChu() {
        initComponents();
        setTitle("Quản lý bán hàng");
        setResizable(false);//Vô hiệu hóa nút phóng to     
        getContentPane().setBackground(Color.WHITE);//Background đổi màu
        
        jtpView.setLayout(new BorderLayout());
        if (bhJPanel==null) {
            bhJPanel = new JPanelBanHang();
            
            jtpView.addTab("Bán hàng", bhJPanel);
        }
        //Gọi panel vừa được thêm vào jtpView
        jtpView.setSelectedComponent(bhJPanel);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnTrangChu = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        jlbTrangChu = new javax.swing.JLabel();
        jbtBanHangJPanel = new javax.swing.JButton();
        jbtSanPhamJPanel = new javax.swing.JButton();
        jbtHoaDonJPanel = new javax.swing.JButton();
        jbtThoat = new javax.swing.JButton();
        jbtPhieuNhapJPanel = new javax.swing.JButton();
        jbtThongKeJPanel = new javax.swing.JButton();
        jtpView = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jpnTrangChu.setBackground(new java.awt.Color(255, 255, 255));
        jpnTrangChu.setForeground(new java.awt.Color(255, 255, 255));

        jpnMenu.setBackground(new java.awt.Color(0, 153, 255));

        jlbTrangChu.setBackground(new java.awt.Color(0, 153, 255));
        jlbTrangChu.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jlbTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        jlbTrangChu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbTrangChu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon_TrangChu.png"))); // NOI18N
        jlbTrangChu.setText("QUẢN LÝ CỬA HÀNG");

        jbtBanHangJPanel.setBackground(new java.awt.Color(0, 153, 255));
        jbtBanHangJPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtBanHangJPanel.setForeground(new java.awt.Color(255, 255, 255));
        jbtBanHangJPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon_BanHang.png"))); // NOI18N
        jbtBanHangJPanel.setText("BÁN HÀNG");
        jbtBanHangJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBanHangJPanelActionPerformed(evt);
            }
        });

        jbtSanPhamJPanel.setBackground(new java.awt.Color(0, 153, 255));
        jbtSanPhamJPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtSanPhamJPanel.setForeground(new java.awt.Color(255, 255, 255));
        jbtSanPhamJPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon_SanPham.png"))); // NOI18N
        jbtSanPhamJPanel.setText("SẢN PHẨM");
        jbtSanPhamJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSanPhamJPanelActionPerformed(evt);
            }
        });

        jbtHoaDonJPanel.setBackground(new java.awt.Color(0, 153, 255));
        jbtHoaDonJPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtHoaDonJPanel.setForeground(new java.awt.Color(255, 255, 255));
        jbtHoaDonJPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon_HoaDon.png"))); // NOI18N
        jbtHoaDonJPanel.setText("HÓA ĐƠN");
        jbtHoaDonJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtHoaDonJPanelActionPerformed(evt);
            }
        });

        jbtThoat.setBackground(new java.awt.Color(0, 153, 204));
        jbtThoat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtThoat.setForeground(new java.awt.Color(255, 255, 255));
        jbtThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon_Thoat.png"))); // NOI18N
        jbtThoat.setText("THOÁT");
        jbtThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThoatActionPerformed(evt);
            }
        });

        jbtPhieuNhapJPanel.setBackground(new java.awt.Color(0, 153, 204));
        jbtPhieuNhapJPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtPhieuNhapJPanel.setForeground(new java.awt.Color(255, 255, 255));
        jbtPhieuNhapJPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon_PhieuNhap.png"))); // NOI18N
        jbtPhieuNhapJPanel.setText("PHIẾU NHẬP");
        jbtPhieuNhapJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPhieuNhapJPanelActionPerformed(evt);
            }
        });

        jbtThongKeJPanel.setBackground(new java.awt.Color(0, 153, 204));
        jbtThongKeJPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtThongKeJPanel.setForeground(new java.awt.Color(255, 255, 255));
        jbtThongKeJPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon_ThongKe.png"))); // NOI18N
        jbtThongKeJPanel.setText("THỐNG KÊ");
        jbtThongKeJPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtThongKeJPanelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addComponent(jlbTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73)
                .addComponent(jbtBanHangJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jbtSanPhamJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jbtHoaDonJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jbtPhieuNhapJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jbtThongKeJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jbtThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlbTrangChu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                    .addComponent(jbtBanHangJPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtSanPhamJPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtHoaDonJPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtPhieuNhapJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtThongKeJPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtThoat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jtpView.setBackground(new java.awt.Color(255, 255, 255));
        jtpView.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpnTrangChuLayout = new javax.swing.GroupLayout(jpnTrangChu);
        jpnTrangChu.setLayout(jpnTrangChuLayout);
        jpnTrangChuLayout.setHorizontalGroup(
            jpnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jtpView)
        );
        jpnTrangChuLayout.setVerticalGroup(
            jpnTrangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTrangChuLayout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jtpView, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtBanHangJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBanHangJPanelActionPerformed
        if (bhJPanel==null) {
            bhJPanel = new JPanelBanHang();
            
            jtpView.addTab("Bán hàng", bhJPanel);
        }
        //Gọi panel vừa được thêm vào jtpView
        jtpView.setSelectedComponent(bhJPanel);
    }//GEN-LAST:event_jbtBanHangJPanelActionPerformed

    private void jbtThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThoatActionPerformed
        int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn thoát hệ thông không?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtThoatActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //Viền jbtBanHangJPanel
        jbtBanHangJPanel.setBorderPainted(false);
        jbtBanHangJPanel.setContentAreaFilled(false);
        jbtBanHangJPanel.setFocusPainted(false);
        jbtBanHangJPanel.setOpaque(false);
        //Viền jbtSanPhamJPanel
        jbtSanPhamJPanel.setBorderPainted(false);
        jbtSanPhamJPanel.setContentAreaFilled(false);
        jbtSanPhamJPanel.setFocusPainted(false);
        jbtSanPhamJPanel.setOpaque(false);
        //Viền jbtHoaDonJPanel
        jbtHoaDonJPanel.setBorderPainted(false);
        jbtHoaDonJPanel.setContentAreaFilled(false);
        jbtHoaDonJPanel.setFocusPainted(false);
        jbtHoaDonJPanel.setOpaque(false);
        //Viền jbtPhieuNhapJPanel
        jbtPhieuNhapJPanel.setBorderPainted(false);
        jbtPhieuNhapJPanel.setContentAreaFilled(false);
        jbtPhieuNhapJPanel.setFocusPainted(false);
        jbtPhieuNhapJPanel.setOpaque(false);
        //Viền jbtThongKeJPanel
        jbtThongKeJPanel.setBorderPainted(false);
        jbtThongKeJPanel.setContentAreaFilled(false);
        jbtThongKeJPanel.setFocusPainted(false);
        jbtThongKeJPanel.setOpaque(false);
        //Viền jbtThoat
        jbtThoat.setBorderPainted(false);
        jbtThoat.setContentAreaFilled(false);
        jbtThoat.setFocusPainted(false);
        jbtThoat.setOpaque(false);
    }//GEN-LAST:event_formWindowOpened

    private void jbtSanPhamJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSanPhamJPanelActionPerformed
        if (spJPanel==null) {
            spJPanel = new JPanelSanPham();
            jtpView.addTab("Sản phẩm", spJPanel);
        }
        jtpView.setSelectedComponent(spJPanel);
    }//GEN-LAST:event_jbtSanPhamJPanelActionPerformed

    private void jbtHoaDonJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtHoaDonJPanelActionPerformed
        if (hdJPanel==null) {
            hdJPanel = new JPanelHoaDon();
            jtpView.addTab("Hóa đơn", hdJPanel);
        }
        jtpView.setSelectedComponent(hdJPanel);
    }//GEN-LAST:event_jbtHoaDonJPanelActionPerformed

    private void jbtThongKeJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtThongKeJPanelActionPerformed
        if (tkJPanel==null) {
            tkJPanel = new JPanelThongKe();
            jtpView.addTab("Thống kê", tkJPanel);
        }
        jtpView.setSelectedComponent(tkJPanel);
    }//GEN-LAST:event_jbtThongKeJPanelActionPerformed

    private void jbtPhieuNhapJPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPhieuNhapJPanelActionPerformed
        if (pnJPanel==null) {
            pnJPanel = new JPanelPhieuNhap();
            jtpView.addTab("Phiếu nhập", pnJPanel);
        }
        jtpView.setSelectedComponent(pnJPanel);
    }//GEN-LAST:event_jbtPhieuNhapJPanelActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtBanHangJPanel;
    private javax.swing.JButton jbtHoaDonJPanel;
    private javax.swing.JButton jbtPhieuNhapJPanel;
    private javax.swing.JButton jbtSanPhamJPanel;
    private javax.swing.JButton jbtThoat;
    private javax.swing.JButton jbtThongKeJPanel;
    private javax.swing.JLabel jlbTrangChu;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnTrangChu;
    private javax.swing.JTabbedPane jtpView;
    // End of variables declaration//GEN-END:variables
}
